### ISSUE TITLE
Best Approach

### ISSUE THREAD

**Issue by johannesschobel** [BrunnerLivio/nestjs-unit-test-db-example#4]
Dear @BrunnerLivio ,

thanks for this example repository on how to use a "testing database".
In my setup, i have `Postgres` as my "main production" database, and would like to use a "sqlite testing" database. However, in my entity definitions i use datatypes, that are not supported by sqlite (i.e., "datetime with timezone" or "json").

How do you cope with such issues?
Or would it be a better approach to use a dedicated docker container for the test-database? What do you think?

All the best

**Comment by BrunnerLivio** [comment]
Hi @johannesschobel 

Yes, I am aware of this.
So one approach would be to just switch the type if an ENV variable is set

```TypeScript
@Column({ type: process.env.NODE_ENV === "test" ? "varchar" : "datetime" })
  size?: string;
```

but that is not really clean, I gotta admit that. Could lead to really unexpected errors down the line.
I think having a dedicated docker container would actually be a better approach. It is a little bit more effort, but at least you are 100% sure that test and production do not have a difference when it comes to the database provider.

**Comment by johannesschobel** [comment]
Dear @BrunnerLivio ,
Thanks a lot for your support. I would vote for the docker-container approach in this case as it may be easier to understand and maintain.

Easiest approach would be to just throw the database away after all tests were executed..

All the best
