### ISSUE TITLE
Booting Test Application

### ISSUE THREAD

**Issue by johannesschobel** [BrunnerLivio/nestjs-unit-test-db-example#5]
Dear @BrunnerLivio ,

sorry to bother you again with this topic.. This may be a kind of stupid question - but:
How do i correctly "boot" the application to be tested? 

For example, i would like to test my API against "real life scenarios", i.e., the e2e-tests should fire against the real application - with all interceptors, middlewares, ... applied that are configured in the `main.ts` file.

If i call
```ts 
const module = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = module.createNestApplication();
    await app.init();
```

the application is correctly booting and can receive calls. However, other configuration parameters i set up in the `main.ts` (for example, adding `globalMiddlewares()` or `globalInterceptors()`) are not applied.

**edit**
i know, that i can just call
```ts
app.useGlobalPrefix(...);
app.useGlobalInterceptors(...);
app.useGlobalMiddlewares(...);
```
but this feels kind of wrong, because i have already defined it somewhere else (`main.ts`)..

Am i missing some key part here?
Thanks a lot!

**Comment by BrunnerLivio** [comment]
@johannesschobel 
Have you thought about extracting this functionality outside of main.ts, like `registerGlobals()`, so you can easily call it from both your `main.ts` and test files

**Comment by johannesschobel** [comment]
Dear @BrunnerLivio , yeah, that would be one approach. However, i was not sure, if this is a "valid" NestJs (and more specifically, a valid `Nrwl/Nx`) approach to do so.

However, i will try to figure this out! Thanks a lot for your help!
